---

- name: Create backend folder
  file:
    path: ~/backend-app
    state: directory

- name: Extract files
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: Build backend
  shell: |
    cd ~/backend-app
    npm i
    npm run build

- name: Start app
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: Print debug message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: Configure PM2 to start as a service
  become: true
  shell: |
    env PATH=$PATH:/user/local/bin pm2 startup systemd -u ubuntu -hp /home/ubuntu
